# 开发模式配置
# 使用方法: docker compose -f compose.yml -f compose.dev.yml up

services:
  backend:
    command: uvicorn arrow_service.main:app --host 0.0.0.0 --port 8000 --reload --loop uvloop
    volumes:
      - ./data:/app/data:ro
      # 挂载代码目录实现热重载
      - ./backend/arrow_service:/app/arrow_service:ro
    labels:
      # 开发模式：添加一个不经过中间件的直连路由
      - "traefik.enable=true"
      - "traefik.http.routers.arrow-dev.rule=Host(`arrow-dev.${DOMAIN:-127.0.0.1.sslip.io}`)"
      - "traefik.http.routers.arrow-dev.entrypoints=websecure"
      - "traefik.http.routers.arrow-dev.tls=true"
      - "traefik.http.routers.arrow-dev.service=arrow-backend-dev-svc"
      - "traefik.http.services.arrow-backend-dev-svc.loadbalancer.server.port=8000"

  # 前端开发模式：挂载构建后的静态文件
  frontend:
    volumes:
      # 挂载本地构建的 dist 目录
      - ./frontend/dist:/usr/share/nginx/html:ro
      # 挂载 dev 模式 nginx 配置（包含 /docs 和 /redoc 代理）
      - ./frontend/nginx.dev.conf.template:/etc/nginx/templates/default.conf.template:ro
