# 开发模式配置
# 使用方法: docker compose -f docker-compose.yml -f compose.dev.yml up

services:
  # 开发环境的后端服务 - 独立容器，支持热重载
  backend-dev:
    build:
      context: ../backend
      dockerfile: Dockerfile
    # 开发环境使用 Granian（支持热重载）
    command: granian arrow_service.main:app --interface asgi --host 0.0.0.0 --port 8000 --workers 1 --http 1 --loop uvloop --reload --log-level debug
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      # 挂载代码目录实现热重载
      - ../backend/arrow_service:/app/arrow_service:ro
      - ../data:/app/data:ro
    networks:
      - default  # 只使用内部网络
    restart: unless-stopped

  # 开发环境的前端服务 - 独立容器
  frontend-dev:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOST=backend-dev
      # 开发环境：1 个 nginx worker（节省资源）
      - NGINX_WORKER_PROCESSES=1
    volumes:
      # 挂载构建后的静态文件
      - ../frontend/dist:/usr/share/nginx/html:ro
      # nginx 配置挂载到 default.conf.template（覆盖 nginx 默认配置）
      - ../frontend/nginx.dev.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - backend-dev
    networks:
      default:
        # 内部网络使用简单服务名
      gateway-http:
        aliases:
          - ${COMPOSE_PROJECT_NAME}-frontend-dev  # 外部网络使用唯一别名
    labels:
      - traefik.enable=true
      # 开发路由：绕过身份认证（路由名使用项目变量避免冲突）
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-arrow-http}-dev.rule=Host(`arrow-dev.${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-arrow-http}-dev.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME:-arrow-http}-dev.middlewares=strip-user-headers@file
      - traefik.http.services.${COMPOSE_PROJECT_NAME:-arrow-http}-dev.loadbalancer.server.port=80
    restart: unless-stopped
